# agent-1/src/reporting/dashboard/dashboard_components.py
import pandas as pd
from datetime import datetime
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from src.reporting.dashboard.dashboard_constants import *
from src.reporting.dashboard.dashboard_styles import _fill, _font, _align, _border, _apply, _section_title
from src.reporting.dashboard.dashboard_charts import _charts_section
from openpyxl.chart import DoughnutChart, Reference
from openpyxl.chart.label import DataLabelList
from src.reporting.dashboard.dashboard_charts import _dLbls, _color_series, DIST_COLORS
from src.reporting.dashboard.dashboard_constants import *
from src.storage.postgres_storage import get_recent_agent_runs

def _col_widths(ws):
    spec = {
        "A":10,  "B":16, "C":12, "D":8,  "E":12,
        "F":12, "G":12, "H":18, "I":16, "J":12,
        "K":10, "L":18, "M":18, "N":12, "O":12,
        "P":12, "Q":14, "R":16, "S":14, "T":14,
    }
    for col, w in spec.items():
        ws.column_dimensions[col].width = w


def _header_and_run_history(ws, metrics, df):
    """
    Rows 1-4: dark navy header bar spanning full width.
    Left side (cols A-K): title + subtitle.
    Right side (cols L-T): Run History table (last 5 runs stub, expandable).
    """
    # ── fill full header area ──
    for r in range(1,4):
        _apply(ws, f"A{r}:P{r}", fill=_fill(DARK_HEADER))

    for r in range(1, 5):
        ws.row_dimensions[r].height = 18

    ws.row_dimensions[1].height = 30

    # Title
    ws.merge_cells("A1:J1")
    c = ws["A1"]
    c.value = "HOTEL ACQUISITION LEADS DASHBOARD"
 
    c.font = Font(
        bold=True,
        size=20,
        color=WHITE,
        name="Arial"
    )
    
    c.fill = _fill(DARK_HEADER)
    
    c.alignment = _align(
        "left",
        "center"
    )
    
    _apply(
        ws,
        "A1:J1",
        fill=_fill(DARK_HEADER)
    )

    # Subtitle
    ws.merge_cells("A2:J2")
    c = ws["A2"]
    c.value = "AI-Powered Distressed Hospitality Acquisition Intelligence"
    c.font  = Font(size=14, color=WHITE, name="Arial")
    c.fill  = _fill(DARK_HEADER)
    c.alignment = _align("left", "center")

    # Metadata (run date + generated by) below subtitle on left
    ws.merge_cells("A3:J3")
    md = ws["A3"]
    md.value = f" Generated by RedPine AI Agent"
    md.font  = Font(size=8, color="9CA3AF", name="Arial")
    md.fill  = _fill(DARK_HEADER)
    md.alignment = _align("left", "center")

    ws.merge_cells("A4:P4")
    _apply(ws, "A4:P4", fill=_fill(DARK_HEADER))

    # Run Date & Time
    ws["L1"] = "Run Date & Time"
    ws["M1"] = datetime.now().strftime("%b %d, %Y %I:%M %p")
    
    # Search Area
    ws["L2"] = "Search Area"
    ws["M2"] = metrics.get("search_area", "")
    
    # Radius
    ws["L3"] = "Leads Found"
    ws["M3"] = str(metrics["total_hotels"])

    for cell in ["L1","L2","L3"]:
        ws[cell].font = Font(
            size=8,
            color="D1D5DB",
            bold=True
        )
        ws[cell].fill = _fill(DARK_HEADER)
    
    for cell in ["M1","M2","M3"]:
        ws[cell].font = Font(
            size=8,
            color=WHITE
        )
        ws[cell].fill = _fill(DARK_HEADER)
    
def _kpi_cards(ws, metrics):
    card_ranges = [
        ("A5:C8"),
        ("D5:F8"),
        ("G5:I8"),
        ("J5:L8"),
        ("M5:P8"),
    ]

    for row in range(5, 9):
        ws.row_dimensions[row].height = 20

    for idx, (metric_key, label, bg, fg) in enumerate(CARD_DEFS):
        rng = card_ranges[idx]
        ws.merge_cells(rng)

        value = metrics.get(metric_key, "—")

        delta = ""
        start_cell = rng.split(":")[0]
        c = ws[start_cell]
        c.value     = f"{label}\n\n{value}"
        c.font      = Font(bold=True, size=11, color=fg, name="Arial")
        c.fill      = _fill(bg)
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        c.border    = _border("D1D5DB")
        _apply(ws, rng, fill=_fill(bg), border=_border("D1D5DB"))

def _top_opportunities_table(ws, df):
    base = 21
    ws.row_dimensions[base].height = 20
    ws.merge_cells(f"A{base}:P{base}")
    c = ws[f"A{base}"]
    c.value     = "TOP ACQUISITION OPPORTUNITIES"
    c.font      = Font(bold=True, size=11, color=WHITE, name="Arial")
    c.fill      = _fill(GREEN_PRIMARY)
    c.alignment = _align("left", "center")
    _apply(ws, f"A{base}:P{base}", fill=_fill(GREEN_PRIMARY))

    headers = [
    "Rank","Hotel Name","City","State","Opp. Score","AI Rating",
    "Distress Prob.","Franchise Status","Signals",
    "Owner Name","Own. Years",
    "Lead Status","Date Surfaced","Rooms","Notes",
    ]
    hrow = base + 1
    ws.row_dimensions[hrow].height = 20
    for i, h in enumerate(headers):
        c = ws.cell(row=hrow, column=1+i, value=h)
        c.font      = Font(bold=True, size=9, color=WHITE, name="Arial")
        c.fill      = _fill(GREEN_PRIMARY)
        c.alignment = _align("center")
        c.border    = _border("FFFFFF")

    top10 = df.sort_values("final_lead_score", ascending=False).head(10)
    for rank, (_, row) in enumerate(top10.iterrows(), 1):
        r = hrow + rank
        ws.row_dimensions[r].height = 20

        # def cmbs_lbl(row):
        #     if row.get("cmbs_delinquent"):        return "Delinquent"
        #     if row.get("cmbs_special_servicing"): return "Special Svc."
        #     if row.get("cmbs_watchlist"):         return "Watchlist"
        #     return "—"

        def fran_lbl(row):
            brand = row.get("current_brand","")
            if row.get("franchise_affiliated"):
                return f"Affiliated ({brand})" if brand else "Affiliated"
            if "Franchise" in str(row.get("llm_top_distress_signals","")):
                return f"Lost ({brand})" if brand else "Lost"
            return "Independent"

        status = str(row.get("lead_status","New"))
        sc_bg, sc_fg = STATUS_COLORS.get(status, ("E2E8F0", TEXT_DARK))
        prob = row.get("llm_distress_probability")
        if pd.isna(prob):
            prob = 0


        vals = [
            rank,
            row.get("hotel_name",""),
            row.get("city",""),
            row.get("state",""),
            row.get("final_lead_score",""),
            f"★ {row.get('llm_star_rating','')}",
            f"{round(prob*100)}%",
            fran_lbl(row),
            str(row.get("llm_top_distress_signals",""))[:40],
            row.get("owner_name",""),
            row.get("ownership_length_years",""),
            status,
            str(row.get("created_at",""))[:10],
            # cmbs_lbl(row),
            row.get("room_count",""),
            row.get("notes",""),
            ]
 
        left_cols = {1, 7, 8, 9, 10, 15}
        for i, val in enumerate(vals):
            c = ws.cell(row=r, column=1+i, value=val)
            c.font      = Font(size=9, color=TEXT_DARK, name="Arial")
            c.alignment = _align("left" if i in left_cols else "center")
            c.border    = _border()
            if (r - hrow) % 2 == 0:
                c.fill = _fill("F8FAFC")
            # Lead status badge
            if i == 11:
                c.font = Font(bold=True, size=9, color=sc_fg, name="Arial")
                c.fill = _fill(sc_bg)
            
            # CMBS Status
            # if i ==13 and val not in ("-", ""):
            #     c.fill = _fill("FEE2E2")
            #     c.font = Font(bold=True, size=9, color="991B1B", name="Arial")
            # Score color
            if i == 4:
                sv = row.get("final_lead_score", 0) or 0
                if sv >= 80:
                    c.fill = _fill("DCFCE7"); c.font = Font(bold=True,size=9,color="166534",name="Arial")
                elif sv >= 60:
                    c.fill = _fill("FEF9C3"); c.font = Font(bold=True,size=9,color="854D0E",name="Arial")


# ─────────────────────────────────────────────
# Bottom section: Lead Status + Recent Activity
# ─────────────────────────────────────────────
def _add_lead_status_donut(ws, data_ws, df):
    chart = DoughnutChart()
    chart.holeSize = 55
    chart.firstSliceAng = 90
    chart.width = 10.5
    chart.height = 4
    chart.legend.position = "r"

    status_counts = (
        df["lead_status"]
        .fillna("NEW")
        .str.upper()
        .value_counts()
    )

    statuses = [
        "NEW",
        "PURSUING",
        "PASSED",
        "MONITORING",
        "UNDERWRITING"
    ]

    start_row = 201
    for idx, status in enumerate(statuses):
        data_ws.cell(start_row + idx, 1). value=status.title()
        data_ws.cell(start_row + idx, 2). value=status_counts.get(status, 0)

    labels = Reference(
        data_ws,
        min_col=1,
        min_row=201,
        max_row=205
    )

    data = Reference(
        data_ws,
        min_col=2,
        min_row=201,
        max_row=205
    )

    chart.add_data(data, titles_from_data=False)
    chart.set_categories(labels)

    chart.series[0].dLbls = _dLbls(show_val=False, show_pct=False)

    _color_series(chart.series[0], LEAD_STATUS_COLORS)
    ws.add_chart(chart, "A35")

def _bottom_section(ws, df, metrics, data_ws):
    br = 34

    # ── Lead Status Overview ──
    _section_title(ws, f"A{br}:F{br}", "Lead Status Overview")
    ws.row_dimensions[br].height = 18
    ws.merge_cells("F35:F41")
    ws["F35"] = ""

    _add_lead_status_donut(ws, data_ws, df)

    # ── Recent Activity ──
    _section_title(ws, f"G{br}:K{br}", "Recent Activity")
    activities = [
        ("🟢",
        f"{metrics['high_opportunity']} high-opportunity leads identified",
        "Current run"),
        ("🔴",
        f"{metrics['deep_distress']} distressed assets detected",
        "Distress scan"),
        ("🔵",
        f"{metrics['total_hotels']} hotels analyzed",
        "Market scan"),
        ("✅",
        "Dashboard generated",
        datetime.now().strftime("%I:%M %p"))
    ]

    for i, (icon, msg, ts) in enumerate(activities):
        r = br + 1 + i
        ws.row_dimensions[r].height = 18
        ws.cell(r, 7,  icon).font = Font(size=10, name="Arial")
        mc = ws.cell(r, 8, msg)
        mc.font = Font(size=9, color=TEXT_DARK, name="Arial")
        tc = ws.cell(r, 9, ts)
        tc.font = Font(size=9, color=TEXT_MED, italic=True, name="Arial")
    
    
    ws.merge_cells("J35:J41")
    ws["J35"] = ""

    ws.merge_cells("K35:K41")
    ws["K35"] = ""

    # - Run History -
    _section_title(ws, f"L{br}:P{br}", "Run History")
    headers=["Run Date", "Search Area", "Leads Found", "New Leads", "Duplicates"]

    run_data = [
        datetime.now().strftime("%b %d %Y"),
        metrics.get("search_area", ""),
        metrics.get("total_hotels", 0),
        metrics.get("high_opportunity", 0),
        0
    ]
    
    for idx, val in enumerate(run_data):
        c = ws.cell(row=br+2, column=12+idx, value=val)
        c.font = Font(size=8, color=TEXT_DARK, name="Arial")
        c.alignment = _align("center")
        c.border = _border()
    
    runs = get_recent_agent_runs(5)

    for idx, h in enumerate(headers):
        c = ws.cell(row=br+1, column=12+idx, value=h)
        c.font      = Font(bold=True, size=8, color=WHITE, name="Arial")
        c.fill      = _fill(GREEN_PRIMARY)
        c.alignment = _align("center")
        c.border    = _border("FFFFFF")
    
    for row_idx, run in enumerate(runs, start=br+2):
        values = [
            run[0].strftime("%b %d %Y"),
            run[1],
            run[2],
            run[3],
            run[4],
        ]

        for col_idx, value in enumerate(values):
            cell = ws.cell(
                row=row_idx,
                column=12 + col_idx,
                value=value
            )

            cell.font = Font(size=8)
            cell.alignment = _align("center")
            cell.border = _border()

            if row_idx % 2 == 0:
                cell.fill = _fill("F8FAFC")


def build_dashboard(ws, data_ws, metrics, df):
    _col_widths(ws)
    _header_and_run_history(ws, metrics, df)
    _kpi_cards(ws, metrics)
    _charts_section(ws, data_ws, df)
    ws.merge_cells("A20:P20")
    ws["A20"] = ""
    _top_opportunities_table(ws, df)
    ws.merge_cells("A33:P33")
    ws["A33"] = ""
    _bottom_section(ws, df, metrics, data_ws)
